apiVersion: v2
name: jupyter-neurohackademy-org
description: A Helm chart to install all parts that make up the hub.neurohackademy.org deployment.
type: application
version: 0.1.0

dependencies:
  # JupyterHub
  - name: jupyterhub
    version: 0.9.0-n150.h1ce17ed
    repository: https://jupyterhub.github.io/helm-chart/

  # Prometheus for collection of metrics.
  # https://hub.helm.sh/charts/stable/prometheus
  - name: prometheus
    version: 11.6.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    tags:
      - metrics

  # Grafana for dashboarding of metrics.
  # https://hub.helm.sh/charts/stable/grafana
  - name: grafana
    version: 5.3.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    tags:
      - metrics
